default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dsi
  username: admin
  password: 
  host: localhost
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
